__id__ = "quick_back"
__name__ = "Quick Back"
__description__ = "Через некоторое насилие над предиктивным жестом происходит магия... А какая я не скажу"
__icon__ = "nonPlugins/2"
__version__ = "0.2"
__min_version__ = "12.5.1"
__author__ = "@nonPlugins"
