__id__ = "quick_back"
__name__ = "Quick Back"
__description__ = "Быстрый возврат к списку чатов при удержании предиктивного жеста или свайпа экрана."
__icon__ = "nonPlugins/2"
__version__ = "0.3"
__min_version__ = "12.1.1"
__author__ = "@nonPlugins"
